# Generated by Django 5.0.4 on 2024-05-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name_plural': 'Doctors'},
        ),
    ]
